# site settings
baseurl: "" # the subpath of the website
highlighter: pygments
paginate: 3
paginate_path: "/page:num"

# build settings
exclude: ["Gemfile", "Gemfile.lock"]

# variables settings
$bgcolor: #F0EDEC;
$iconcolor: #C2B8B4;
$fontcolor: #736157;
$textcolor: #666666;
$shadowcolor: #6A6F6F;

# Gems
gems: [jekyll-paginate]